### ISSUE TITLE
How to Implement Mouse Scroll?

### ISSUE THREAD

**Issue by gurkanlus** [mehmet-erim/ngx-slickjs#13]
is there any way of implement wheel scroll without jqury just defining event binding? couldnt see any event about that . Anybody know how to do?

**Comment by mehmet-erim** [comment]
There is any way. See the example on Stackblitz:
https://stackblitz.com/edit/ngx-slickjs-mousewheel

**Comment by mehmet-erim** [comment]
Version 1.5.0 has been released and added to the mouse wheel feature.
