### ISSUE TITLE
ngx-slickJS initial slide option not working in angular 8 

### ISSUE THREAD

**Issue by rahulh11041996** [mehmet-erim/ngx-slickjs#14]
i created a slider in angular using ngx-slickJS and its working fine, but i need to show 3rd slide initially but its not working

newsDetails: Slick.Config = {
infinite: false,
slidesToShow: 1,
slidesToScroll: 1,
dots: false,
autoplay: false,
fade: true,
speed: 300,
easing: 'linear',
mouseWheelMove: false,
initialSlide: 2
}

**Comment by mehmet-erim** [comment]
Hello @rahulh11041996 

The problem has been fixed, you can install the new version with the following command:

```bash
yarn add ngx-slickjs@1.5.2
```

Thanks for the reporting
